### ISSUE TITLE
Can't open any transition or activity after resizing the designer drawing area via resize button

### ISSUE THREAD

**Issue by Yousefjb** [optimajet/WorkflowEngine.NET#10]
#### Reproduce
- Open the workflow designer  
- Change area width ( 1200 to 1800 as example )
- Press resize  
- no transition or activity can open now

**Comment by dmelnikov** [comment]
Hello.

Is the case reproduce on demo.workflowenginenet.com demo-stand?
I'm have used Google Chrome and I can't reproduced it.

Also, please, read the post about typical throubles: http://workflowenginenet.com/Documentation/Detail/FAQ_DESIGNERTROUBLESHOOTING

**Comment by Yousefjb** [comment]
I couldn't reproduce it in the demo designer. It appears to be relative to my chrome 51.0.2704  on windows server 2010 since IE 11 works perfectly. Since no error in the chrome console i don't think there is much can be done.  

Thanks.
