### ISSUE TITLE
Workflow engine designer doesn't work

### ISSUE THREAD

**Issue by jopalesha** [optimajet/WorkflowEngine.NET#103]
Hi!

https://workflowengine.io/demo/designer/
Can't Download, Upload xml scheme

error 413: Request Entity Too Large See more info in the browser console.

![image](https://user-images.githubusercontent.com/15217146/146896892-c4d0d235-caac-4b2e-93d2-5f4476f52932.png)

**Comment by shalugin** [comment]
@jopalesha Thank you for pointing this out to us. We've fixed this bug.
