### ISSUE TITLE
Workflow desinger Download xml button throws 500 error

### ISSUE THREAD

**Issue by jopalesha** [optimajet/WorkflowEngine.NET#104]
POST https://workflowengine.io/demo/Designer/API method throws 500 error for my scheme:

Maximum request length exceeded.

Response with stacktrace in attachments
[response.txt](https://github.com/optimajet/WorkflowEngine.NET/files/7761121/response.txt)

**Comment by shalugin** [comment]
@jopalesha Can you send us your scheme? What is the size of your scheme?

**Comment by jopalesha** [comment]
@shalugin can't reproduce now. I think we can close the ticket
