### ISSUE TITLE
Question : Can a process live in two activites at the same time ?

### ISSUE THREAD

**Issue by Yousefjb** [optimajet/WorkflowEngine.NET#11]
If a process is at activity A and i want the process to move to activity B and C with the same command.

**Comment by dmelnikov** [comment]
WFE will check access for move for the user, after that will chose any first allowed transition.

**Comment by Yousefjb** [comment]
So i assume it is not possible for a process to be in two activites, right ? I guess i can represent it via multiple workflows.

**Comment by dmelnikov** [comment]
I don't understand what you want to do.
Please, send more information about this case as support ticket to our support service.
