### ISSUE TITLE
Creating a new subproccess takes about 1-3 seconds

### ISSUE THREAD

**Issue by Yousefjb** [optimajet/WorkflowEngine.NET#12]
When i create a new subprocess like in the following picture there is always a delay compared to direct commands.

[![Untitled.png](https://s16.postimg.org/wmal8o91x/Untitled.png)](https://postimg.org/image/k7nt8chjl/)

the transition from `Licensing` to `TrainingApp` have a condition which simply just a `return true` . 
the same happens at CreateGurantee activity, where both of these activites start a new process.

Any ideas of why is it slow and how could i improve it ?

**Comment by dmelnikov** [comment]
Yousefjb, I have no idea, need to review your sample.
Do you have a support agreement?

**Comment by zeadkhalid** [comment]
Hi Dmitry,

Yousefjb is a member in our development team (Isra' Software & Computer Co),
To reproduce the issue about the slow when reach a sub-process you can use a sample Scheme in the attached file (scheme_SubProcess.zip).

[scheme_SubProcess.zip](https://github.com/optimajet/WorkflowEngine.NET/files/444035/scheme_SubProcess.zip)

when the process reach the 2nd activity (DirectManager) it will check a condition called (CheckNeedValue)
which only return true;
always moved to the activity (DirectManager2) and if the condition is true will create a sub-process for activity (AltEmp).

**Comment by dmelnikov** [comment]
According to [SLA](http://workflowenginenet.com/SLA), please, use email.
