### ISSUE TITLE
Enable action debugging while in release mode and there is no debuggers attached throws an excpetion and force close the application

### ISSUE THREAD

**Issue by Yousefjb** [optimajet/WorkflowEngine.NET#13]

**Comment by dmelnikov** [comment]
Please, describe this trouble more.

**Comment by Yousefjb** [comment]
If you try to edit an action code via the designer and set the comment `/*break*/` to indicate a break point and enable action dubug via `runtime.CodeActionDebugOn()` then insted of hitting F5 in visual studio to run the debugger you can press Ctrl + F5 which start the application (my app) without the debugger, when the workflow engine reachs the `/*break*/` and try to execute it it will hang the app and need to force close it.
However, if insted of writing `/*break/` you can write : 
```
#if DEBUG 
/*break*/ 
#endif
```
and everything works smoothly

**Comment by dmelnikov** [comment]
We will fix it in the next version of WFE.
