### ISSUE TITLE
can not complie

### ISSUE THREAD

**Issue by RaulSteven** [optimajet/WorkflowEngine.NET#15]
`严重性  代码  说明  项目  文件  行 禁止显示状态
错误      This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Users\Administrator\Source\Repos\WorkflowEngine.NET\Samples\MSSQL\\.nuget\NuGet.targets.    WF.Sample.Business  C:\Users\Administrator\Source\Repos\WorkflowEngine.NET\Samples\MSSQL\WF.Sample.Business\WF.Sample.Business.csproj   124 
`

i can not find ".nuget"

**Comment by dmelnikov** [comment]
Look at the link: http://stackoverflow.com/questions/22909506/this-project-references-nuget-packages-that-are-missing-on-this-computer
