### ISSUE TITLE
how can i change the language into chinese

### ISSUE THREAD

**Issue by i542873057** [optimajet/WorkflowEngine.NET#19]
the  workflowengine is perfect well,but the language is all english,it is very inconvenient,is there any language package integrate in it

**Comment by optimajet** [comment]
Hello.

Do you ask about the user interface or documentation?

For localization the user interface you need to change properties into WorkflowDesignerConstants js-object. The object using for rendering labels.
[This file](https://github.com/optimajet/WorkflowEngine.NET/blob/master/SnippetCode/DesignerCostants.js) has the struct of WorkflowDesignerConstants object.
