### ISSUE TITLE
Hard to use - the Samples from your website are missing

### ISSUE THREAD

**Issue by papyr** [optimajet/WorkflowEngine.NET#2]
Hi optima, after trying this and spending a lot of time, I noticed there are **no true _useable_ samples like the ones listed on your website, for e.g. the document approval system** is show on the site but not here. Aldo you have multiple connections strings that are colliding
-    Its no use without have a full working sample, since its hard to understand and follow (non-trivial), I would suggest that you please rename the basic names like _sightings_ etc... 
-    In the sample can you list and **include role/user management** 
  -   _so make it easy to integrate with an existing web MVC_ application with ASP identity 2.2. This would make the purchase easier since the effort to integrate would be turnkey.
  -   right now since we don't know your source / design, its hard to know where to tie-in or integrate our user and role checks for the document approval
-    Can you have the designer **auto detect** the screen-size
  -  what is the purpose of a new besides the resize button, does it allow me to create a full new instance or schema??
  -  can you allow zooming in and panning out so we can see full designer
  -  can you change the color of the arrow, and command actions
  -  can you explain how to use command actions, actions, transitions, executions
-    Can you list more documentation on the simple document approval for admin, manager and user actor perspectives. Its not clear who is doing what
-    It has **potential but buggy like the previous users mentioned**
-    Can you include a mini-map like photoshop at the corner
-    What happened to all the settings previously?

**Comment by dmelnikov** [comment]
Dear Papyr.

WFE is simple for use, more simple than any other workflow product.
For understanding concept use workflow you need understand the diagram: http://bit.ly/1IizhHi .

WFE is provide basic functional workflow for document approval. Not more.
All additional requirements we ready to make for your company for fee. 

I will try to add your suggestions in our roadmap, but it depends on sales.
Thanks you.
