### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by dopare** [optimajet/WorkflowEngine.NET#21]
Are there any plans to use .NET Standard ?

**Comment by optimajet** [comment]
The last version of WFE has built on .NET Standard.
https://www.nuget.org/packages/WorkflowEngine.NETCore-Core/

**Comment by dopare** [comment]
Thanks, so it is totally different package.
It is not listed in https://workflowengine.io/downloads/

**Comment by optimajet** [comment]
Click on .NET Core on the header toolbar in https://workflowengine.io/downloads/

**Comment by dopare** [comment]
Didn't notice the sub menu :D
