### ISSUE TITLE
Customize Menu (Activities and Templates) of WorkflowEngine

### ISSUE THREAD

**Issue by naourez-zouaoui** [optimajet/WorkflowEngine.NET#212]
Hello, 
I was wondering how to remove some Activities and Template for the existing one the default menu as you can see in below picture.
![image](https://github.com/optimajet/WorkflowEngine.NET/assets/155728214/7adbf5f8-9f6e-4ed5-be06-c29ddec27521)

![image](https://github.com/optimajet/WorkflowEngine.NET/assets/155728214/3f20acf6-e0c1-41f1-be8e-c23f69e9bcd9)

**Comment by optimajet** [comment]
@naourez-zouaoui There are simple steps to do this:

1. Copy existing Designer templates from https://github.com/optimajet/WorkflowEngine.NET/tree/master/Designer/templates to your folder.
2. Set the Designer `templatefolder` property - it should point to the folder with your templates from step 1 (see example in this guide - https://workflowengine.io/documentation/react-integration-from-scratch#adding-designer-component).
3. Fix the `elements.html` template (https://github.com/optimajet/WorkflowEngine.NET/blob/master/Designer/templates/elements.html#L7, https://github.com/optimajet/WorkflowEngine.NET/blob/master/Designer/templates/elements.html#L24).

By changing the designer templates you can almost completely change the appearance of the product.
