### ISSUE TITLE
Workflow Engine rollback?

### ISSUE THREAD

**Issue by kekovespa** [optimajet/WorkflowEngine.NET#22]
Hi,
Is there any rollback implementation already built on workflow Engine?
Thanks

**Comment by optimajet** [comment]
Hi.
WFE hasn't such API method for it. You might determine the previous state and call SetState method.
If it has an exception while WFE's executing process, use OnWorkflowError event ([Error handling](https://workflowengine.io/documentation/execution/regular-process/));

**Comment by kekovespa** [comment]
How can I throw a WFE exception?

**Comment by optimajet** [comment]
Please, read the article from previous post up to end
