### ISSUE TITLE
Integration with AspNet Boilerplate suggestions

### ISSUE THREAD

**Issue by ebicoglu** [optimajet/WorkflowEngine.NET#24]
My suggestions for the sample [AspnetBoilerplate & Workflow integration code](https://github.com/optimajet/WorkflowEngine.NET/tree/master/Other/AngularBoilerplate)

- [DocumentAppService ](https://github.com/optimajet/WorkflowEngine.NET/blob/master/Other/AngularBoilerplate/aspnet-core/src/AngularBPWorkflow.Application/Documents/DocumentAppService.cs#L23)needs permission otherwise it can be run anonymous users from WebAPI. You can add permission to the whole application service or to a method. See https://aspnetboilerplate.com/Pages/Documents/Authorization#using-abpauthorize-attribute

- You can rename `WorkflowInit `=> `WorkflowManager`

- Database migration is not being managed by Entity Framework so it needs to be run externally.
I created a new migration with your SQL migration scripts that updates database automatically when `update-database` runs... so no need to run scripts externally.
[20190118115540_Workflow_Db_Changes._EntityFramework_Migration.zip](https://github.com/optimajet/WorkflowEngine.NET/files/2772861/20190118115540_Workflow_Db_Changes.zip)

**Comment by optimajet** [comment]
Alper, thanks for your recommendations.

We've improved the sample: ([commint 430e3df0043738b1a3945a87ebf732ddf70589c2](https://github.com/optimajet/WorkflowEngine.NET/commit/430e3df0043738b1a3945a87ebf732ddf70589c2))
