### ISSUE TITLE
Getting Warning : package not fully compatible with your project

### ISSUE THREAD

**Issue by mvshete** [optimajet/WorkflowEngine.NET#26]
Getting a warning with Visual Studio 2019 Class Library(.NET Standard & .NET Core) project

By adding the following NuGet packages into the project

**WorkflowEngine.NET-Core
WorkflowEngine.NET-ProviderForMSSQL**

Below are the warnings

Package 'WorkflowEngine.NET-ProviderForMSSQL 4.0.7' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	WorkFlow.Library	C:\Users\XXX\source\repos\WorkFlowSolution\WorkFlow.Library\WorkFlow.Library.csproj	1
	
Package 'WorkflowEngine.NET-Core 4.0.7' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	WorkFlow.Library	C:\Users\XXX\source\repos\WorkFlowSolution\WorkFlow.Library\WorkFlow.Library.csproj	1	

![c1](https://user-images.githubusercontent.com/25241093/58415575-7e13ef80-809c-11e9-837d-e6e1cd757d74.PNG)

**Comment by optimajet** [comment]
For .NET Core use WorkflowEngine.NETCore-Core and WorkflowEngine.NETCore-ProviderForMSSQL packages.

**Comment by mvshete** [comment]
If you look at the above message & snapshot, I have used the same.
