### ISSUE TITLE
File is not copied only link

### ISSUE THREAD

**Issue by mvshete** [optimajet/WorkflowEngine.NET#27]
Why installing package **WorkflowEngine.NETCore-Designer** adds a link to the file in wwwroot & not the actual file?

![image](https://user-images.githubusercontent.com/25241093/64949231-5b4d5700-d896-11e9-94f1-faed059b6e4e.png)

**Comment by optimajet** [comment]
It is not the package issue, but the behavior for "new" type of VS project. You can find more information here https://stackoverflow.com/questions/50677740/vs2017-nuget-package-files-treated-as-link-instead-of-actual-file
