### ISSUE TITLE
Console Application- Getting Error on CreateInstance

### ISSUE THREAD

**Issue by Jeevanbr** [optimajet/WorkflowEngine.NET#3]
While loading WorkflowApp.WorkflowInit.Runtime.CreateInstance method. Getting the below error in console application.

(Using section): error CS0246: The type or namespace name 'WF' could not be found (are you missing a using directive or an assembly reference?)

Please help to fix this error.

**Comment by dmelnikov** [comment]
Dear Jeevenbr, 

this error because of WFE tried build CodeActions. A usings-block of one CodeActions include 'WF' namespace, but in your project don't have the namespace. Your need will check CodeActions in the scheme.

**Comment by Jeevanbr** [comment]
Got resolved. Removed Code action from the schema. thanks a lot.

**Comment by PrakashThiru14** [comment]
Dear dmelnikov,
I have added WF namespace in CodeAction block, but still saying same error. anything else I need to add?

**Comment by dmelnikov** [comment]
What an error do you have?

**Comment by PrakashThiru14** [comment]
The error is, (Using section): error CS0246: The type or namespace name 'WF' could not be found (are you missing a using directive or an assembly reference?). Should I need to remove WF namespace in Code action? If I remove it is working fine. But If I remove 'WF' namespace, I am unable to access WorkflowInit class from Code action.

**Comment by dmelnikov** [comment]
Because your application has no WF namespace. You need to add the reference to your project.

For more information, please, ask the support.

**Comment by trelloscy** [comment]
I'm getting the exact same error in your sample application which theoretically should work out of the box... Could you please explain what exactly we need to change in the code to make the [https://workflowengine.io/downloads/how-to-integrate.zip](url) project run?

**Comment by optimajet** [comment]
Check Using in each CodeActions in your scheme

https://workflowengine.io/documentation/scheme/actions/#creation

**Comment by trelloscy** [comment]
> Check Using in each CodeActions in your scheme
> 
> https://workflowengine.io/documentation/scheme/actions/#creation

Thanks for the prompt reply! We are trying to evaluate the simplicity of the WorkflowEngine by executing the finished sample application targeting the sample _Vacation Request_ workflow generated by the provided t-sql scripts. We have not specified any custom CodeActions in our code, we just run the _how-to-integrate_ application and keep getting the **namespace name 'WF' could not be found** exception.

**Comment by optimajet** [comment]
Please, share the scheme.
