### ISSUE TITLE
blazor support

### ISSUE THREAD

**Issue by j209** [optimajet/WorkflowEngine.NET#39]
Hi
any plan for support [blazor](https://github.com/aspnet/Blazor)?

**Comment by optimajet** [comment]
Our backlog has the task of making offline the mode for WFE. Perhaps when Blazor WebAssembly reaches maturity, we will get to this task and use it. If you have more ideas or suggestions please feel free to write them on Github or support@optimajet.com.

**Comment by mserey** [comment]
Hi, 
any news about this?
