### ISSUE TITLE
Not opensource - mostly dlls

### ISSUE THREAD

**Issue by winecraft** [optimajet/WorkflowEngine.NET#4]
Because I had an error while building the DW kit, I was trying to resolve that and pulling this down to include in the place of the Dll's to build, but I am still getting errors? _It was only then that I found out, this is mostly dlls' and not open source - no source code is included._ 
-         Can you clearly tell me where I can pull down your dll's source and build myself. 
-         Where are they - or are you not including them... this does not seem opensource to me

<b>Everything here is mostly prebuilt dll's, but no source, a little source for some HTML and MVC views and interfaces not the business layer or the core app, seems to me as marketing only - not really open source</b>

<b>Another user pointed out the same issue</b> http://workflowengine.codeplex.com/discussions/528507 and **you moved here** to a different repository! 

Like he says 
"kiquenet
<i>Jan 31, 2014 at 7:38 AM
   <b>The project is open source ? if it's not, why is hosted in codeplex? "... </b> 

GitHub is for open source only please, and **_not marketing**_ . If you want a commercial closed source you have to buy a different package at Github, this is totally false</i>

Total waste of time.

**Comment by dmelnikov** [comment]
Thanks for your interest to our product.
The repository has source code of environment around WFE.
We don't publish the source code of one library - OptimaJet.Workflow.Core.dll. 

Codeplex have source code of old version 1.1. If you want we may publish the source code of version 1.1 on this place.

>Can you clearly tell me where I can pull down your dll's source and build myself.
>Where are they - or are you not including them... this does not seem opensource to me

For non-commercial use you may get the source code of WFE 1.1 on codeplex: https://workflowengine.codeplex.com/SourceControl/latest#WFE 1.1/
