### ISSUE TITLE
can't go through  my own database 

### ISSUE THREAD

**Issue by Hamza23579** [optimajet/WorkflowEngine.NET#40]
Hi,
I am trying to Check if a value is greater that a number and for that I need to query form my database ( some purchase Tabe where there is the price ).
The senario goes like this: 
   - If the price is greater than 50000 then User1 must approve the purchase demand
   - otherwise User2 is the one who has to approve.
The same thing happens when I want to Check the User with the ruleCheck that I created.
I get this error: 

System.ArgumentException : 'Format of the initialization string does not conform to specification starting at index 0.'

Here is the function that I do in the Condition:
`        
private DatabaseContext context = new DatabaseContext("DefaultConnection");

public bool checkMontant(string numeroCommande, int montant)
        {
            CommandeDataModel c = context.Commandes.FirstOrDefault(c => c.Numero.Equals(numeroCommande));
            return (c.Montant <= montant) ? true : false;
        }`

In the condition code I put this code : 
`Class c = new Class();
return c.checkMontant("112", 50000);`

And also in the Designer It shows no compilation errors.

**Comment by optimajet** [comment]
Correspond to the exception message, most likely you made a typo in the connection string. Please check it.

**Comment by Hamza23579** [comment]
It wasn't the connection string but how I did use it.
I just solved this problem and this is how it worked:

 var optionsBuilder = new DbContextOptionsBuilder<DatabaseContext>();
            optionsBuilder.UseSqlServer("My Connection String");

            using (var context = new DatabaseContext(optionsBuilder.Options))
            {
                // do stuff
                CommandeDataModel c = context.Commandes.FirstOrDefault(c => c.Numero.Equals(numeroCommande));
                return (c.Montant <= montant) ? true : false;
            }
Thank you.
