### ISSUE TITLE
Integrate Users in WFE as Actors

### ISSUE THREAD

**Issue by Hamza23579** [optimajet/WorkflowEngine.NET#41]
Hi,
I want to be able to use my users table as the actors that I create in the designer.
If that is possible please fill me with full instructions.
Thank you.

**Comment by optimajet** [comment]
Please read the following documentation topics:
https://workflowengine.io/documentation/faq/workflow-server/manage-roles/
https://workflowengine.io/documentation/faq/workflow-engine/manage-roles/
https://workflowengine.io/documentation/scheme/rules/
