### ISSUE TITLE
GetAvailableCommands return an empty array

### ISSUE THREAD

**Issue by Hamza23579** [optimajet/WorkflowEngine.NET#42]
Hi,
I am trying to get available commands but all I get is an empty array.
The function worked just fine but now I am having this issue.
Any ideas on what the problem might be?
Thank you.

**Comment by optimajet** [comment]
Hi,
Most likely, some of your authorization rules attached to a transition, returned false. 
If you want more help please write details to support@optimajet.com.

**Comment by Hamza23579** [comment]
okay Thanks
