### ISSUE TITLE
Support dot net core

### ISSUE THREAD

**Issue by amira133** [optimajet/WorkflowEngine.NET#49]
hello,
do you support dot net core?
if yes do you support dot net core 3?

thanks ...

**Comment by optimajet** [comment]
Yes, the Workflow Engine supports .net core.  And it supports .net core 3.  Our examples are using .net core 2.1 but you can connect our packages to the  .net core 3 projects and it will work. You can download samples here https://workflowengine.io/downloads/net-core/
