### ISSUE TITLE
This is simply not useable as opensource very misleading;  NOT really OpenSource

### ISSUE THREAD

**Issue by patagoniahiker** [optimajet/WorkflowEngine.NET#5]
I was on the other doc sample, and then I downloaded and tried this to step in, could not figure out/trace the debug on whats going on for the longest time, then realized **its only some of the code** (and samples) is available. But the rest is really private and commercial!

<h3>Why are the main dlls and the designers are all closed source? and only under commercial license<h3> - this is simply not usable as open source, and very misleading

Also the designer actions and words make no sense, don't correspond with user actions buggy. 

<h3>do you really have an opensource community version or not??</h3> If not, IMHO you're doing this a s a SCAM.

**Comment by dmelnikov** [comment]
I answered about the source code, but you don't read an other issue before create the issue.
I repeat my answer:

The repository has source code of environment around WFE.
We don't publish the source code of one library - OptimaJet.Workflow.Core.dll.
Codeplex have source code of old version 1.1. If you want we may publish the source code of version 1.1 on this place. For non-commercial use you may get the source code of WFE 1.1 on codeplex: https://workflowengine.codeplex.com/SourceControl/latest#WFE 1.1/

**Comment by patagoniahiker** [comment]
How exactly is that going to work - this version with an older version of the core? So, in fact this is not really usable since the core is never published, it seems to me like a bait and switch. where is the current version of the core and what license is that under - can that be used in the community version?

And, yes this is non-commercial, like a majority of github users.

**Comment by dmelnikov** [comment]
The old version don't support some features, but format of scheme almost the same.

I think your requirements is very big for free product from commercial company.  Try use an other product or this product as is for non-commercial project.

**Comment by patagoniahiker** [comment]
How would you know what my requirements are??

This project is not opensource, currently does not compile, hard to understand. (which is fine/understandable, if they could be resolved). But then you want me to buy commercial license because the core parts are sealed and commercial licensed - really!! scammy salesman- IMHO!

**Comment by dmelnikov** [comment]
Yes, we published the old version as open source for marketing.
We do not hide it.

If you use open source or free version then you must ready to learn without support, yourself.
I hope you may chose the best workflow product for your project. 

Good luck to you!
