### ISSUE TITLE
Drag Activity from Toolbar instead of click the Activity from the toolbar

### ISSUE THREAD

**Issue by softtechinfo2020** [optimajet/WorkflowEngine.NET#57]
I need drag activity from the toolbar instead of click the Activity from the toolbar.Anyone can you please help me

**Comment by optimajet** [comment]
This will be available in WFE 5.0, which will be available this September.

**Comment by softtechinfo2020** [comment]
Thanks for your response .When will be available in WFE 5.0

**Comment by optimajet** [comment]
it will be available at the end of the September.
