### ISSUE TITLE
Uncaught TypeError: t.window.dialog is not a function

### ISSUE THREAD

**Issue by NintavurWings** [optimajet/WorkflowEngine.NET#6]
getting error when i click on Actives, Commands, Parameters, Localization, Timers, code Action and Additional parameters.

![001](https://cloud.githubusercontent.com/assets/11376239/11371510/f1050e20-92d9-11e5-9955-92b084b8eae5.png)

**Comment by dmelnikov** [comment]
You don't init library JqueryUI.
Mot information about designer troubles you may read on the page:
http://workflowenginenet.com/Documentation/Detail/FAQ_DESIGNERTROUBLESHOOTING

**Comment by VaishaliSelvam** [comment]
I am getting the same error. I have initialised the JqueryUI.
