### ISSUE TITLE
Passing Parameters from Angular to Active Current Custom Activity

### ISSUE THREAD

**Issue by softtechinfo2020** [optimajet/WorkflowEngine.NET#66]
Currently am using WFE 4.2.2 and Creating some custom activity tool.
Have to implement some functionality.
Currently we used WFE 4.2.2 and Angular 9
Based on selecting  activity from Canvas area am showing right side window.
I need to pass right windows values to that particular activity and when i select that same activity should populate that related selection and enter values in right side window.
Anyone can please kindly help to fix this.
Screen shot attached here
Note: Instead of Jquery popup window am using right panel window;
![image](https://user-images.githubusercontent.com/58630781/94407955-c613bc80-0191-11eb-9ecf-aa12a0da0923.png)

**Comment by optimajet** [comment]
We have just published WFE 5.0 with a completely new Designer. Look at this https://workflowengine.io/demo/designer/. We don't use modal windows anymore. And you can customize each window. Additionally, you can drag'n'drop Activities from the Elements panel. Just click the Elements button in the toolbar and drag any activity on the canvas.

**Comment by softtechinfo2020** [comment]
Hi ,
Thank you for your reply,
I need to drag activity directly from toobar instead of drag  activity from
element popup

**Comment by optimajet** [comment]
In the new version, you can completely customize toolbars, https://github.com/optimajet/WorkflowEngine.NET/blob/master/Designer/templates/toolbar.html, and create the toolbar with drag'n'drop if you want.

**Comment by softtechinfo2020** [comment]
Thanks for your reply.
I tried this way only and now I can able to customize toolbar but I can't
able to do drag and drop functionality.please help me or share those line
of code

**Comment by optimajet** [comment]
Hi,
you can use the new version to modify the toolbar to fit your needs or 
taste using HTML.


Regards,

Timur K.
Presales Engineer
OptimaJet LLC

------ Original Message ------
From: "'softtechinfo2020' via support" <support@optimajet.com>
To: "optimajet/WorkflowEngine.NET" 
<WorkflowEngine.NET@noreply.github.com>
Cc: "OptimaJet" <support@optimajet.com>; "Comment" 
<comment@noreply.github.com>
Sent: 10/9/2020 7:22:14 PM
Subject: Re: [optimajet/WorkflowEngine.NET] Passing Parameters from 
Angular to Active Current Custom Activity (#66)

**Comment by optimajet** [comment]
You can look at drag'n'drop here https://github.com/optimajet/WorkflowEngine.NET/blob/master/Designer/templates/elements.html just combine two of this templates.
