### ISSUE TITLE
About DynamicParameter

### ISSUE THREAD

**Issue by doubleceston** [optimajet/WorkflowEngine.NET#67]
hi,
   I have read your article about  `parameters` here :https://workflowengine.io/documentation/scheme/parameters/
   and I'm curious about `DynamicParameter `
   but i can't find it's definition or model in api reference here:https://workflowengine.io/api-reference/annotated.html

**Comment by doubleceston** [comment]
Okay, thank you for your timely reply

Can I trouble you to update the document? Cause  it's more concise and effective

**Comment by optimajet** [comment]
Thanks for the comment, I created a task to update the API reference.
