### ISSUE TITLE
How to delete the temp files that generated by workflow instance.

### ISSUE THREAD

**Issue by jerrylisuzhou** [optimajet/WorkflowEngine.NET#69]
In fact , I use the workflow.engine for a long time and found no disk space in disk C.   Finally , we found in account temp directory , there are many many temp files that generated by workflow .  When workflow instance start , it will create new files always.  so how to delete them safety ? I am not sure if your framework can remove it automatically . 

file path://
C:\Users\xxxx\AppData\Local\Temp

**Comment by optimajet** [comment]
Hi, 
The WFE doesn't create any files for its work. Are you sure it's not your business logic that creates them? Please send more information to support@optimajet.com.

**Comment by optimajet** [comment]
Although you may have debug code actions enabled. Then turn it off and delete the files.

**Comment by jerrylisuzhou** [comment]
Yes , on debug mode now .    Thank you , I will close it  .  

runtime.CodeActionsDebugOn();

**Comment by optimajet** [comment]
Ok, thank you for the report.
