### ISSUE TITLE
How to Reset screen Activity and Transition

### ISSUE THREAD

**Issue by softtechinfo2020** [optimajet/WorkflowEngine.NET#71]
I would like to know how to reset drawn activity and transition in WFD 5.0

**Comment by optimajet** [comment]
Click on the R button in the left panel.

**Comment by softtechinfo2020** [comment]
It has been removed all the local storage data but i need only drawn activities reset

**Comment by optimajet** [comment]
It looks like the workflow engine has no the feature.
 Send the feature request to sales@optimaje.com.
