### ISSUE TITLE
About Activity action executions

### ISSUE THREAD

**Issue by doubleceston** [optimajet/WorkflowEngine.NET#72]
hi ,
    when i try to run a process (all auto trigger transitions), I found that activities (exclude the initial one) didn't run their actions ,  and i read the source code, found it only executed transition without the activity's action in method `executeFull`
    can you help me to find what's wrong with my usage?

**Comment by optimajet** [comment]
hi, can you send your scheme to support@optimajet.com

**Comment by doubleceston** [comment]
it is very simple, i can post here:

`<process id="21" name="flowSample" canBeInlined="false" tags="">

    <parameters>
        <parameter name="Amount" purpose="TEMPORARY"
                   implementation="com.pdd.qingzhou.sdk.parameter.QueryAmountService"/>
    </parameters>

    <actions>
        <action name="FightForQZ" implementation="com.pdd.qingzhou.sdk.actions.ActionMocker"/>
    </actions>

    <activities>
        <activity name="enroll" state="101" isInitial="True" isFinal="False" isForSetState="True">
            <actions>
                <action order="1" name="FightForQZ"/>
            </actions>
        </activity>

        <activity name="audit" state="102" isInitial="False" isFinal="False" isForSetState="True">
            <actions>

            </actions>

        </activity>
        <activity name="pass" state="103" isInitial="False" isFinal="False" isForSetState="True">
            <actions>

            </actions>

        </activity>
        <activity name="refuse" state="104" isInitial="False" isFinal="False" isForSetState="True">
            <actions>

            </actions>

        </activity>
        <activity name="push" state="501" isInitial="False" isFinal="True" isForSetState="True">
            <actions>

            </actions>
        </activity>

    </activities>

    <transitions>
        <transition name="auditToRefuse" to="refuse" from="audit" classifier="DIRECT" allowConcatenationType="AND"
                    conditionsConcatenationType="AND" disableParentStateControl="false">
            <triggers>
                <trigger type="AUTO"/>
            </triggers>
            <conditions>
                <condition type="OTHERWISE"/>
            </conditions>
        </transition>

        <transition name="auditToPass" to="pass" from="audit" classifier="DIRECT" allowConcatenationType="AND"
                    conditionsConcatenationType="AND" disableParentStateControl="false">
            <triggers>
                <trigger type="AUTO"/>
            </triggers>
            <conditions>
                <condition type="ACTION" actionName="FightForQZ" conditionInversion="false"/>
                <condition type="EXPRESSION" conditionInversion="false">
                    <expression><![CDATA[
                        Amount.getTotal() > 50
                    ]]></expression>
                </condition>
                <condition type="EXPRESSION" conditionInversion="false">
                    <expression> <![CDATA[
                        Amount.getTotal() < 60
                    ]]> </expression>
                </condition>
            </conditions>
        </transition>


        <transition name="enrollToAudit" to="audit" from="enroll" classifier="DIRECT" allowConcatenationType="AND"
                    conditionsConcatenationType="AND" disableParentStateControl="false">
            <triggers>
                <trigger type="AUTO"/>
            </triggers>
            <conditions>
                <condition type="ALWAYS"/>
            </conditions>
        </transition>

        <transition name="refuseToPush" to="push" from="pass" classifier="DIRECT" allowConcatenationType="AND"
                    conditionsConcatenationType="AND" disableParentStateControl="false">
            <triggers>
                <trigger type="AUTO"/>
            </triggers>
            <conditions>
                <condition type="ALWAYS"/>
            </conditions>
        </transition>

    </transitions>

</process>`

**Comment by doubleceston** [comment]
just the activity `enroll ` execute it's action
the other activities doesn't run

**Comment by optimajet** [comment]
I can import the scheme - "There are multiple root elements. Line 34, position 2.".
