### ISSUE TITLE
Multi-timers on one activity

### ISSUE THREAD

**Issue by stefansreckovic** [optimajet/WorkflowEngine.NET#73]
Hi,
I have 2 timer triggers on 1 activity (defined as interval) , on transition with some condition. 
When one of them is executed and condition is false, happens that after that both of timers are reseted. If I mark "Do not override timer if exists" as true on timer definition, after evaluating condition as false, timer is not created again on activity. 
What I want is 2 timers (timer interval working as recurring timers) on 1 activity , that work independent.

**Comment by optimajet** [comment]
Hi, this behavior is correct. Try to use the subprocesses (https://workflowengine.io/documentation/execution/subprocesses/) for your case.
