### ISSUE TITLE
DropWorkflowProcesses stored procedure doesn't delete WorkflowProcessInstancePersistence records

### ISSUE THREAD

**Issue by ronaldbosma** [optimajet/WorkflowEngine.NET#75]
Hi,

I noticed that the DropWorkflowProcesses stored procedure doesn't delete records from the WorkflowProcessInstancePersistence table. On this line it queries the persistence table, but deletes records from the status table: https://github.com/optimajet/WorkflowEngine.NET/blob/d91b5e977db565500c76a1a94e151ff425773187/Other/AngularBoilerplate/db/SQL/CreatePersistenceObjects.sql#L201

I was wondering if this is a bug or by design?

**Comment by betine** [comment]
Hi,
DropWorkflowProcesses  is not used anymore, actual scripts for databases can be found here https://github.com/optimajet/WorkflowEngine.NET/blob/master/Providers/OptimaJet.Workflow.MSSQL/Scripts/CreatePersistenceObjects.sql
