### ISSUE TITLE
nuget and db updates out of sync

### ISSUE THREAD

**Issue by patagoniahiker** [optimajet/WorkflowEngine.NET#8]
After downloading this via nuget, and trying I noticed the package builds on 4.5 and not 4.6.1 and also has compile issues due to many packages out of sync.

**Comment by dmelnikov** [comment]
>>I noticed the package builds on 4.5 and not 4.6.1
Is it a problem for you?

>>also has compile issues due to many packages out of sync.
What issues do your have?

**Comment by patagoniahiker** [comment]
when I try to put all the components together, it has build issues and dependencies after updates... try it out for yourself. Next I get parse error from Javascript on not defined value `:` when an edit is restored back from the db, i.e. the designer is loaded back

**Comment by dmelnikov** [comment]
I can't reproduce it by your description.
Please, send the request to support.
