### ISSUE TITLE
CommandExecutionResult should contain more information

### ISSUE THREAD

**Issue by CodeThag** [optimajet/WorkflowEngine.NET#94]
CommandExecutionResult class should return more information in the event of ExecuteCommand or ExecuteCommandAsync resulting in a negative result due to failed condition test

Users should be told exactly what condition(s) were not met and not just a bool.

**Comment by optimajet** [comment]
Dear CodeThag.

Could you describe your case?

**Comment by CodeThag** [comment]
For instance, a document requires two conditions to be fulfilled before approval. If one of the conditions is not fulfilled, WorkflowEngine does not return the condition name instead CommandExecutionResult just returns a false status. It will be nice to know which condition was not met.

**Comment by optimajet** [comment]
Ok, I've registered the feature in our backlog.

**Comment by CodeThag** [comment]
Please, what is the update on this?

**Comment by optimajet** [comment]
Dear @CodeThag,

This is planned for version 7.x after we release version 7.0.
The release of version 7.0 is scheduled for the next two weeks.
